# Generated by Django 5.2.16 on 2026-07-15 06:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PatientReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("external_id", models.CharField(max_length=128)),
                ("mrn_hash", models.CharField(blank=True, default="", max_length=64)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "external_id"),
                        name="uq_patient_ref_tenant_external",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("code_system", models.CharField(max_length=32)),
                ("code", models.CharField(max_length=64)),
                ("marker", models.CharField(db_index=True, max_length=64)),
                ("value", models.FloatField()),
                ("unit", models.CharField(max_length=32)),
                ("original_value", models.FloatField()),
                (
                    "original_unit",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("observed_at", models.DateTimeField()),
                ("inbound_message_id", models.UUIDField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="clinical_data.patientreference",
                    ),
                ),
            ],
            options={
                "ordering": ["-observed_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "patient", "marker", "observed_at"],
                        name="clinical_da_tenant__9bdb46_idx",
                    )
                ],
            },
        ),
    ]
