# Generated by Django 5.2.16 on 2026-07-15 06:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OperationsQueueItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("unmapped_code", "Unmapped code"),
                            ("unsupported_unit", "Unsupported unit"),
                            ("failed_event", "Failed event"),
                            ("no_patient_match", "No patient match"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=200)),
                ("detail", models.CharField(blank=True, default="", max_length=255)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "kind", "status"],
                        name="operations__tenant__891d50_idx",
                    )
                ],
            },
        ),
    ]
