# Generated by Django 5.2.16 on 2026-07-15 06:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IntegrationMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("code_system", models.CharField(max_length=32)),
                ("code", models.CharField(max_length=64)),
                ("marker", models.CharField(max_length=64)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "code_system", "code"),
                        name="uq_mapping_tenant_system_code",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MappingProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("code_system", models.CharField(max_length=32)),
                ("code", models.CharField(max_length=64)),
                ("seen_count", models.PositiveIntegerField(default=1)),
                ("sample_payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "code_system", "code"),
                        name="uq_proposal_tenant_system_code",
                    )
                ],
            },
        ),
    ]
