# Generated by Django 5.2.16 on 2026-07-15 20:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PurgeRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled minimization"),
                            ("termination", "BAA termination hard-purge"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("dry_run", models.BooleanField(default=False)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("executed_by", models.CharField(default="system", max_length=128)),
                ("cutoffs", models.JSONField(default=dict)),
                ("purged_counts", models.JSONField(default=dict)),
                ("total_purged", models.PositiveIntegerField(default=0)),
                ("audit_events_retained", models.PositiveIntegerField(default=0)),
                (
                    "certificate_hash",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "mode"],
                        name="retention_p_tenant__dfbd25_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RetentionPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("window_overrides", models.JSONField(default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "updated_by",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("terminated", models.BooleanField(db_index=True, default=False)),
                ("terminated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id"], name="retention_r_tenant__dce8d0_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id",), name="uq_retention_policy_tenant"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CertificateOfDestruction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled minimization"),
                            ("termination", "BAA termination hard-purge"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("dry_run", models.BooleanField(default=False)),
                ("lines", models.JSONField(default=list)),
                ("total_purged", models.PositiveIntegerField(default=0)),
                ("audit_events_retained", models.PositiveIntegerField(default=0)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "purge_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="retention.purgerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "mode"],
                        name="retention_c_tenant__a0b771_idx",
                    )
                ],
            },
        ),
    ]
