# Generated by Django 5.2.16 on 2026-07-15 19:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodingSuggestionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("workflow_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("patient_external_id", models.CharField(max_length=128)),
                (
                    "encounter_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "snapshot_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("suggestion_type", models.CharField(max_length=32)),
                ("icd10_code", models.CharField(max_length=16)),
                ("description", models.CharField(max_length=256)),
                ("hcc", models.CharField(blank=True, default="", max_length=64)),
                (
                    "supersedes_code",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("requires_provider_confirmation", models.BooleanField(default=True)),
                ("rationale", models.TextField(blank=True, default="")),
                ("evidence", models.JSONField(default=list)),
                ("dedup_key", models.CharField(db_index=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("confirmed", "Confirmed by clinician"),
                            ("rejected", "Rejected"),
                            ("exported", "Exported to coding/claim"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "decided_by",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"],
                        name="coding_codi_tenant__d4502b_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "workflow_id"],
                        name="coding_codi_tenant__8f8361_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "tenant_id",
                            "patient_external_id",
                            "encounter_id",
                            "dedup_key",
                        ),
                        name="uq_coding_suggestion_per_gap",
                    )
                ],
            },
        ),
    ]
