# Generated by Django 5.2.16 on 2026-07-15 13:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KillSwitchRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("tenant", "Tenant"),
                            ("site", "Site"),
                            ("specialty", "Specialty"),
                            ("workflow", "Workflow"),
                            ("protocol", "Protocol"),
                            ("clinician", "Clinician"),
                            ("model_provider", "Model_Provider"),
                            ("integration", "Integration"),
                            ("communication_channel", "Communication_Channel"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("target", models.CharField(default="*", max_length=200)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "engaged_by",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("engaged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "released_by",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("released_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-engaged_at"],
                "indexes": [
                    models.Index(
                        fields=["active", "scope"], name="killswitch__active_039304_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("scope", "target"),
                        name="uniq_active_killswitch_per_scope_target",
                    )
                ],
            },
        ),
    ]
