# Generated by Django 5.2.16 on 2026-07-15 07:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("key", models.SlugField(max_length=96)),
                ("marker", models.CharField(db_index=True, max_length=64)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "key"), name="uq_protocol_tenant_key"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProtocolVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("version", models.PositiveIntegerField()),
                ("rule_body", models.JSONField()),
                ("evidence_references", models.JSONField(default=list)),
                (
                    "state",
                    models.CharField(db_index=True, default="draft", max_length=16),
                ),
                (
                    "clinical_approved_by",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "engineering_approved_by",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("impact_report", models.JSONField(blank=True, null=True)),
                ("test_results", models.JSONField(default=list)),
                ("author", models.CharField(blank=True, default="", max_length=128)),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="protocols.protocol",
                    ),
                ),
            ],
            options={
                "ordering": ["protocol_id", "-version"],
            },
        ),
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("shadow", "Shadow"),
                            ("progressive", "Progressive rollout"),
                            ("full", "Full"),
                        ],
                        max_length=16,
                    ),
                ),
                ("rollout_percentage", models.PositiveIntegerField(default=100)),
                ("target_scope", models.JSONField(default=dict)),
                (
                    "rollback_to_version",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("monitoring_plan", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("rolled_back", "Rolled back"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("conflicts_suppressed", models.BooleanField(default=False)),
                (
                    "deployed_by",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployments",
                        to="protocols.protocolversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Rollback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("from_version", models.PositiveIntegerField()),
                ("to_version", models.PositiveIntegerField(blank=True, null=True)),
                ("automatic", models.BooleanField(default=False)),
                ("reason", models.CharField(max_length=255)),
                ("actor", models.CharField(blank=True, default="", max_length=128)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rollbacks",
                        to="protocols.deployment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RuleTestCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=128)),
                ("marker", models.CharField(max_length=64)),
                ("specialty", models.CharField(blank=True, default="", max_length=64)),
                ("facts", models.JSONField(default=dict)),
                ("conflicting_facts", models.JSONField(default=list)),
                ("expected_classification", models.CharField(max_length=48)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="protocols.protocolversion",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SimulationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("scenario_count", models.PositiveIntegerField(default=0)),
                ("changed_count", models.PositiveIntegerField(default=0)),
                ("agreement_rate", models.FloatField(default=1.0)),
                ("cases", models.JSONField(default=list)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulations",
                        to="protocols.protocolversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="protocolversion",
            index=models.Index(
                fields=["tenant_id", "state"], name="protocols_p_tenant__d42b2b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="protocolversion",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "protocol", "version"),
                name="uq_version_protocol_number",
            ),
        ),
        migrations.AddIndex(
            model_name="deployment",
            index=models.Index(
                fields=["tenant_id", "status", "mode"],
                name="protocols_d_tenant__db9c4f_idx",
            ),
        ),
    ]
