# Generated by Django 5.2.16 on 2026-07-15 13:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DisasterRecoveryDrill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                (
                    "outcome",
                    models.CharField(
                        choices=[("passed", "Passed"), ("failed", "Failed")],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                ("rpo_met", models.BooleanField()),
                ("rto_met", models.BooleanField()),
                ("data_loss_seconds", models.FloatField()),
                ("downtime_seconds", models.FloatField()),
                ("replay_count", models.PositiveIntegerField(default=0)),
                ("stranded_count", models.PositiveIntegerField(default=0)),
                ("notes", models.JSONField(default=list)),
                ("ran_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-ran_at"],
            },
        ),
    ]
