# Generated by Django 5.2.16 on 2026-07-15 07:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboundMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("ehr_task", "EHR task/inbox"),
                            ("patient_portal", "Patient portal message"),
                        ],
                        max_length=20,
                    ),
                ),
                ("workflow_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("target", models.CharField(max_length=200)),
                ("subject", models.CharField(blank=True, default="", max_length=200)),
                ("body", models.TextField(blank=True, default="")),
                ("idempotency_key", models.CharField(max_length=200, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status", "channel"],
                        name="delivery_ou_tenant__4867d4_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeliveryAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("succeeded", models.BooleanField(default=False)),
                ("detail", models.CharField(blank=True, default="", max_length=255)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="delivery.outboundmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
