# Generated by Django 5.2.16 on 2026-07-15 06:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor", models.CharField(max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("authentication", "Authentication"),
                            ("phi_access", "PHI access"),
                            ("rule_create", "Rule creation"),
                            ("rule_modify", "Rule modification"),
                            ("rule_approve", "Rule approval"),
                            ("rule_deploy", "Rule deployment"),
                            ("config_change", "Configuration change"),
                            ("mapping_change", "Mapping change"),
                            ("workflow_decision", "Workflow decision"),
                            ("llm_usage", "LLM usage"),
                            ("message_delivery", "Message delivery"),
                            ("clinician_action", "Clinician action"),
                            ("admin_export", "Administrative export"),
                            ("support_access", "Support access"),
                            ("data_purge", "Data purge"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("resource", models.CharField(max_length=255)),
                ("tenant_id", models.UUIDField(db_index=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("session", models.CharField(blank=True, max_length=128, null=True)),
                ("before_state", models.JSONField(blank=True, null=True)),
                ("after_state", models.JSONField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, default="")),
                ("correlation_id", models.CharField(db_index=True, max_length=64)),
                ("prev_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("record_hash", models.CharField(db_index=True, max_length=64)),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "timestamp"],
                        name="audit_audit_tenant__400cee_idx",
                    )
                ],
            },
        ),
    ]
