# Generated by Django 5.2.16 on 2026-07-15 13:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttestationRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("window_label", models.CharField(max_length=120)),
                ("frameworks", models.JSONField(default=list)),
                ("attested", models.BooleanField(db_index=True)),
                ("evidence_digest", models.CharField(db_index=True, max_length=64)),
                ("controls", models.JSONField(default=list)),
                ("gaps", models.JSONField(default=list)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
    ]
