# Generated by Django 5.2.16 on 2026-07-15 06:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkflowInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("workflow_type", models.CharField(default="results", max_length=32)),
                ("correlation_id", models.CharField(db_index=True, max_length=64)),
                ("patient_external_id", models.CharField(max_length=128)),
                ("observation_id", models.UUIDField(blank=True, null=True)),
                ("marker", models.CharField(max_length=64)),
                ("classification", models.CharField(max_length=48)),
                ("priority", models.CharField(max_length=16)),
                ("automation_status", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending review"),
                            ("approved", "Approved"),
                            ("edited", "Edited & approved"),
                            ("overridden", "Overridden"),
                            ("escalated", "Escalated"),
                            ("closed", "Closed"),
                            ("blocked", "Blocked (unsupported)"),
                            ("suppressed", "Automation suppressed"),
                        ],
                        db_index=True,
                        default="pending_review",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status", "priority"],
                        name="workflows_w_tenant__b17bde_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProtocolEvaluationRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("marker", models.CharField(max_length=64)),
                (
                    "matched_rule_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "matched_rule_version",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("critical_triggered", models.BooleanField(default=False)),
                ("decision", models.JSONField()),
                ("trace", models.JSONField()),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="workflows.workflowinstance",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HumanReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("edit", "Edit & approve"),
                            ("override", "Override"),
                            ("escalate", "Escalate"),
                            ("reject", "Reject"),
                            ("close", "Close"),
                        ],
                        max_length=16,
                    ),
                ),
                ("actor", models.CharField(max_length=128)),
                ("edited_message", models.TextField(blank=True, default="")),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="workflows.workflowinstance",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedCommunication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "template_key",
                    models.CharField(blank=True, default="", max_length=96),
                ),
                ("patient_message", models.TextField(blank=True, default="")),
                ("clinician_summary", models.TextField(blank=True, default="")),
                ("validation_passed", models.BooleanField(default=False)),
                ("validation_failures", models.JSONField(default=list)),
                ("used_fallback", models.BooleanField(default=False)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communications",
                        to="workflows.workflowinstance",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Escalation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("reason", models.CharField(max_length=255)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations",
                        to="workflows.workflowinstance",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
