# Generated by Django 5.2.16 on 2026-07-15 19:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpecialtyThresholdPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("specialty", models.CharField(db_index=True, max_length=64)),
                ("overrides", models.JSONField(default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "updated_by",
                    models.CharField(blank=True, default="", max_length=128),
                ),
            ],
            options={
                "ordering": ["specialty"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "specialty"],
                        name="specialties_tenant__a82e6b_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "specialty"),
                        name="uq_specialty_threshold_policy",
                    )
                ],
            },
        ),
    ]
