# Generated by Django 5.2.16 on 2026-07-15 07:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PatientMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("correlation_id", models.CharField(db_index=True, max_length=64)),
                (
                    "patient_external_id",
                    models.CharField(db_index=True, max_length=128),
                ),
                ("channel", models.CharField(default="patient_portal", max_length=48)),
                ("original_text", models.TextField()),
                ("language", models.CharField(default="en", max_length=8)),
                ("category", models.CharField(blank=True, default="", max_length=32)),
                ("urgency", models.CharField(blank=True, default="", max_length=32)),
                ("red_flags", models.JSONField(default=list)),
                ("reason_codes", models.JSONField(default=list)),
                (
                    "destination",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("auto_resolvable", models.BooleanField(default=False)),
                ("draft_response", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("triaged", "Triaged"),
                            ("escalated", "Escalated"),
                            ("resolved", "Resolved"),
                            ("routed", "Routed"),
                            ("blocked", "Blocked (identity)"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status", "urgency"],
                        name="patient_mes_tenant__f3b855_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MessageReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("respond", "Respond"),
                            ("route", "Route"),
                            ("escalate", "Escalate"),
                            ("resolve", "Resolve"),
                        ],
                        max_length=16,
                    ),
                ),
                ("actor", models.CharField(max_length=128)),
                ("response_text", models.TextField(blank=True, default="")),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="patient_messages.patientmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageClassificationRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("category", models.CharField(max_length=32)),
                ("confidence", models.FloatField(default=0.0)),
                ("urgency", models.CharField(max_length=32)),
                ("red_flags", models.JSONField(default=list)),
                ("symptoms", models.JSONField(default=list)),
                ("medications", models.JSONField(default=list)),
                ("summary", models.TextField(blank=True, default="")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classifications",
                        to="patient_messages.patientmessage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
