# Generated by Django 5.2.16 on 2026-07-15 06:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DomainEventOutbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True, null=True)),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("schema_version", models.PositiveIntegerField(default=1)),
                ("correlation_id", models.CharField(db_index=True, max_length=64)),
                (
                    "causation_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("idempotency_key", models.CharField(max_length=200, unique=True)),
                ("payload", models.JSONField()),
                ("audit_metadata", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                            ("dead_letter", "Dead letter"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="core_domain_status_10d261_idx",
                    )
                ],
            },
        ),
    ]
