# Generated by Django 5.2.16 on 2026-07-15 17:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from core.rls import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EhrConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("issuer", models.CharField(max_length=512, unique=True)),
                ("vendor", models.CharField(default="epic", max_length=32)),
                ("client_id", models.CharField(max_length=255)),
                ("redirect_uri", models.CharField(max_length=512)),
                ("scopes", models.JSONField(default=list)),
                ("active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["issuer", "active"],
                        name="embedded_eh_issuer_2d569c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EhrIdentityLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("subject", models.CharField(db_index=True, max_length=255)),
                ("active", models.BooleanField(db_index=True, default=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_links",
                        to="embedded.ehrconnection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ehr_identity_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "subject"],
                        name="embedded_eh_tenant__979633_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("connection", "subject"), name="uniq_connection_subject"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EhrLaunchSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("state", models.CharField(db_index=True, max_length=64, unique=True)),
                ("nonce", models.CharField(max_length=64)),
                ("issuer", models.CharField(max_length=512)),
                ("token_url", models.CharField(blank=True, default="", max_length=512)),
                (
                    "launch_token",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("denied", "Denied"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "patient_context",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "encounter_context",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="launch_sessions",
                        to="embedded.ehrconnection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ehr_launches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"],
                        name="embedded_eh_tenant__c65080_idx",
                    )
                ],
            },
        ),
        # RLS on the identity-bridge table only: it is resolved AFTER the tenant is bound, so
        # database-enforced isolation applies. EhrConnection (issuer→tenant routing) and
        # EhrLaunchSession (keyed by an unguessable state) are resolved during the still-
        # unauthenticated launch/callback — before any tenant context exists — so they are
        # deliberately left outside the per-tenant policy (see models docstring).
        enable_rls("embedded_ehridentitylink"),
    ]
