# Generated by Django 5.2.16 on 2026-07-15 06:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContextSnapshotRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("workflow_id", models.UUIDField(db_index=True)),
                ("patient_external_id", models.CharField(max_length=128)),
                ("snapshot_hash", models.CharField(db_index=True, max_length=64)),
                ("facts", models.JSONField()),
                ("provenance", models.JSONField()),
                ("builder_version", models.CharField(max_length=32)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "workflow_id"],
                        name="context_con_tenant__b85b09_idx",
                    )
                ],
            },
        ),
    ]
