# Generated by Django 5.2.16 on 2026-07-15 08:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PatientResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("workflow_type", models.CharField(max_length=32)),
                ("workflow_id", models.UUIDField(db_index=True)),
                ("responded", models.BooleanField(default=False)),
                ("sentiment", models.CharField(blank=True, default="", max_length=16)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProtocolFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("protocol_key", models.CharField(db_index=True, max_length=96)),
                ("signal", models.CharField(max_length=64)),
                ("detail", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClinicianFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("workflow_type", models.CharField(max_length=32)),
                ("workflow_id", models.UUIDField(db_index=True)),
                ("practitioner", models.CharField(db_index=True, max_length=128)),
                ("action", models.CharField(max_length=16)),
                (
                    "protocol_key",
                    models.CharField(blank=True, default="", max_length=96),
                ),
                ("specialty", models.CharField(blank=True, default="", max_length=64)),
                ("original_text", models.TextField(blank=True, default="")),
                ("edited_text", models.TextField(blank=True, default="")),
                ("edit_difference", models.JSONField(default=dict)),
                ("reason", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "workflow_type", "action"],
                        name="feedback_cl_tenant__a4b86a_idx",
                    )
                ],
            },
        ),
    ]
