# Generated by Django 5.2.16 on 2026-07-15 13:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SLOBreachRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slo_key", models.CharField(db_index=True, max_length=64)),
                ("description", models.CharField(max_length=255)),
                ("observed", models.FloatField()),
                ("target", models.FloatField()),
                (
                    "window_label",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["slo_key", "detected_at"],
                        name="reliability_slo_key_333a0c_idx",
                    )
                ],
            },
        ),
    ]
