# Generated by Django 5.2.16 on 2026-07-15 08:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("scope", models.CharField(db_index=True, max_length=48)),
                ("metrics", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConfigurationRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("kind", models.CharField(max_length=48)),
                ("target", models.CharField(max_length=128)),
                ("proposal", models.JSONField(default=dict)),
                ("rationale", models.TextField(blank=True, default="")),
                ("supporting_observations", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("deployed", "Deployed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "deployment_ref",
                    models.CharField(blank=True, default="", max_length=128),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status", "kind"],
                        name="analytics_c_tenant__a81919_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PractitionerPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("practitioner", models.CharField(db_index=True, max_length=128)),
                ("adjustments", models.JSONField(default=dict)),
                ("derived_from", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["practitioner"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "practitioner"),
                        name="uq_preference_practitioner",
                    )
                ],
            },
        ),
    ]
