# Generated by Django 5.2.16 on 2026-07-15 13:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreakGlassGrantRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("responder", models.CharField(db_index=True, max_length=200)),
                ("reason", models.TextField()),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("revoked", models.BooleanField(db_index=True, default=False)),
                (
                    "revoked_by",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-granted_at"],
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("platform_administrator", "Platform Admin"),
                    ("tenant_administrator", "Tenant Admin"),
                    ("clinical_programmer", "Clinical Programmer"),
                    ("clinical_reviewer", "Clinical Reviewer"),
                    ("integration_engineer", "Integration Engineer"),
                    ("support_engineer", "Support Engineer"),
                    ("security_reviewer", "Security Reviewer"),
                    ("read_only_auditor", "Read Only Auditor"),
                    ("clinician", "Clinician"),
                    ("nurse", "Nurse"),
                    ("operations_analyst", "Operations Analyst"),
                    ("emergency_responder", "Emergency Responder"),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
