# Generated by Django 5.2.16 on 2026-07-15 07:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AllergyIntolerance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "patient_external_id",
                    models.CharField(db_index=True, max_length=128),
                ),
                ("substance", models.CharField(max_length=128)),
            ],
            options={
                "ordering": ["substance"],
            },
        ),
        migrations.CreateModel(
            name="ClientMonitoringPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("med_class", models.CharField(max_length=32)),
                ("requires_monitoring_labs", models.BooleanField(default=False)),
                (
                    "visit_required_within_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("auto_approve", models.BooleanField(default=False)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "med_class"),
                        name="uq_monitoring_policy_class",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MedicationStatement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "patient_external_id",
                    models.CharField(db_index=True, max_length=128),
                ),
                ("rxnorm", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=200)),
                ("med_class", models.CharField(max_length=32)),
                ("schedule", models.CharField(default="none", max_length=8)),
                (
                    "prescribed_dose",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("active", models.BooleanField(default=True)),
                ("discontinued", models.BooleanField(default=False)),
                ("days_supply", models.PositiveIntegerField(blank=True, null=True)),
                ("last_fill_days_ago", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "patient_external_id", "rxnorm"],
                        name="refills_med_tenant__c6755d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RefillWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("workflow_type", models.CharField(default="refill", max_length=32)),
                ("correlation_id", models.CharField(db_index=True, max_length=64)),
                ("patient_external_id", models.CharField(max_length=128)),
                ("rxnorm", models.CharField(max_length=32)),
                (
                    "medication_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "requested_dose",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("outcome", models.CharField(max_length=40)),
                ("controlled_substance", models.BooleanField(default=False)),
                ("automation_allowed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending review"),
                            ("auto_approved", "Auto-approved"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("escalated", "Escalated"),
                            ("routed", "Routed"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="pending_review",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status", "outcome"],
                        name="refills_ref_tenant__6828e5_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RefillReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("route", "Route"),
                            ("escalate", "Escalate"),
                        ],
                        max_length=16,
                    ),
                ),
                ("actor", models.CharField(max_length=128)),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="refills.refillworkflow",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="RefillEvaluationRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("outcome", models.CharField(max_length=40)),
                ("reason_codes", models.JSONField(default=list)),
                ("required_actions", models.JSONField(default=list)),
                ("clinical_factors_used", models.JSONField(default=list)),
                ("decision", models.JSONField()),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="refills.refillworkflow",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
